files:
  - source: /frappe/locale/main.pot
    translation: /frappe/locale/%locale_with_underscore%.po
pull_request_title: "fix: sync translations from crowdin"
pull_request_labels:
  - translation
  - skip-release-notes
commit_message: "fix: %language% translations"
append_commit_message: false
languages_mapping:
  locale_with_underscore:
    ar_SA: ar
    bs_BA: bs
    de_DE: de
    eo_UY: eo
    es_ES: es
    fa_IR: fa
    fr_FR: fr
    hr_HR: hr
    hu_HU: hu
    pl_PL: pl
    ru_RU: ru
    sv_SE: sv
    th_TH: th
    tr_TR: tr
    zh_CN: zh
